package com.thesis.pickleballserve

import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Test

/**
 * Golden parity tests for PaddleStream logic against fixtures generated by
 * scripts/gen_paddle_stream_fixtures.py from the offline python pipeline.
 */
class PaddleStreamLogicTest {

    private fun fixture(): JSONObject =
        JSONObject(javaClass.classLoader!!.getResource("fixtures/paddle_stream.json")!!.readText())

    private fun speeds(clip: JSONObject): List<Double> {
        val arr = clip.getJSONArray("speeds")
        return (0 until arr.length()).map { arr.getDouble(it) }
    }

    private fun angles(clip: JSONObject): List<Pair<Int, Double>> {
        val arr = clip.getJSONArray("angles")
        return (0 until arr.length()).map {
            val a = arr.getJSONArray(it)
            a.getInt(0) to a.getDouble(1)
        }
    }

    @Test
    fun contactFrameMatchesPythonPipeline() {
        val clips = fixture().getJSONArray("clips")
        for (i in 0 until clips.length()) {
            val c = clips.getJSONObject(i)
            val contact = PaddleStream.contactFrame(speeds(c), c.getInt("t"))
            assertEquals("contact mismatch for ${c.getString("clip_id")}",
                c.getInt("contact"), contact)
        }
    }

    @Test
    fun scalarMatchesPythonPipeline() {
        val clips = fixture().getJSONArray("clips")
        for (i in 0 until clips.length()) {
            val c = clips.getJSONObject(i)
            val contact = PaddleStream.contactFrame(speeds(c), c.getInt("t"))
            val scalar = PaddleStream.scalarFor(angles(c), contact)
            assertEquals("scalar mismatch for ${c.getString("clip_id")}",
                c.getDouble("scalar"), scalar!!, 1e-6)
        }
    }

    @Test
    fun scalarNullWhenNoAngles() {
        assertNull(PaddleStream.scalarFor(emptyList(), 10))
    }

    @Test
    fun coachingDoesNotFallBackToAnAngleOutsideTheContactWindow() {
        val angles = listOf(0 to 90.0, 1 to 100.0)
        assertEquals(95.0, PaddleStream.scalarFor(angles, 20)!!, 1e-6)
        assertNull(PaddleStream.contactScalarFor(angles, 20))
        assertEquals(50.0, PaddleStream.contactScalarFor(angles + (20 to 50.0), 20)!!, 1e-6)
        assertNull(PaddleStream.contactScalarFor(listOf(20 to Double.NaN), 20))
    }

    @Test
    fun verdictUsesBandDirection() {
        val low = 10.4
        val high = 162.2
        assertEquals("PADDLE: --", PaddleStream.verdictFor(null, low, high))
        assertEquals("PADDLE: TOO CLOSED", PaddleStream.verdictFor(5.0, low, high))
        assertEquals("PADDLE: TOO OPEN", PaddleStream.verdictFor(170.0, low, high))
        assertEquals("PADDLE: OPTIMAL", PaddleStream.verdictFor(90.0, low, high))
        assertEquals("PADDLE: OPTIMAL", PaddleStream.verdictFor(low, low, high))
        assertEquals("PADDLE: OPTIMAL", PaddleStream.verdictFor(high, low, high))
    }

    @Test
    fun longAxisAngleMatchesPython() {
        val axis = fixture().getJSONArray("axis")
        for (i in 0 until axis.length()) {
            val a = axis.getJSONObject(i)
            val got = PaddleGeometry.longAxisAngle(
                a.getDouble("w"), a.getDouble("h"), a.getDouble("ang"))
            assertEquals("axis mismatch w=${a.getDouble("w")} h=${a.getDouble("h")} " +
                    "ang=${a.getDouble("ang")}",
                a.getDouble("expected"), got, 1e-9)
        }
    }

    @Test
    fun pickNearestWristBox() {
        val near = PaddleDetector.Det(floatArrayOf(90f, 90f, 110f, 110f), 0.4f)
        val far = PaddleDetector.Det(floatArrayOf(400f, 400f, 440f, 440f), 0.9f)
        val dets = listOf(far, near)
        assertEquals(near, PaddleDetector.pick(dets, 100f, 100f, 300f))
        assertNull(PaddleDetector.pick(dets, 1000f, 1000f, 300f))
        assertEquals(far, PaddleDetector.pick(dets, Float.NaN, 100f, 300f))
        assertNull(PaddleDetector.pick(emptyList(), 100f, 100f, 300f))
    }

    @Test
    fun expandBoxPadsAndTruncates() {
        val r = PaddleGeometry.expandBox(floatArrayOf(100f, 100f, 150f, 150f), 1920, 1080)
        assertEquals(94, r.x)
        assertEquals(94, r.y)
        assertEquals(62, r.width)
        assertEquals(62, r.height)

        val clamped = PaddleGeometry.expandBox(floatArrayOf(-5f, 10f, 90f, 60f), 1920, 1080)
        assertEquals(0, clamped.x)
        assertEquals(4, clamped.y)
        assertEquals(101, clamped.width)
        assertEquals(62, clamped.height)
    }

    @Test
    fun medianMatchesNumpyConvention() {
        assertEquals(3.0, PaddleStream.median(listOf(1.0, 2.0, 3.0, 4.0, 5.0))!!, 0.0)
        assertEquals(2.5, PaddleStream.median(listOf(1.0, 2.0, 3.0, 4.0))!!, 0.0)
        assertEquals(1.0, PaddleStream.median(listOf(1.0, 1.0, 5.0))!!, 0.0)
        assertNull(PaddleStream.median(emptyList()))
    }
}
